spring:
  application:
    name: gestao-vendas

  datasource:
    url: jdbc:postgresql://localhost:5432/gvendas_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: 
          - info
          - health
          - metrics
          - prometheus